run-dist:
	./build/install/app/bin/app

#clean:
#	./gradlew clean
#build:
#	./gradlew clean build
clean:
	./gradlew clean
build:
	./gradlew build
	.PHONY: build
run:
	./gradlew run
report:
	./gradlew jacocoTestReport